import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { v4 as uuid } from 'uuid';
import styles from "../../styles/Home.module.css";
import Button from "../../components/button"

export default function Home() {
  const [todoList, setTodoList] = useState([]);
  const [todoTitle, setTodoTitle] = useState("");

  /** get todo list in the local storage */
  useEffect(() => {
    const todoList = localStorage.getItem("todoList");
    if (todoList) {
      setTodoList(JSON.parse(todoList));
    }
  }, []);

  /** Add TODO in the local storage */
  const addTodo = () => {
    const newTodo = {
      id: uuid(),
      title: todoTitle,
    };
    const newTodoList = [...todoList, newTodo];
    setTodoList(newTodoList);
    localStorage.setItem("todoList", JSON.stringify(newTodoList));
    setTodoTitle("");
  };

  /** Delete TODO in the local storage */
  const deleteTodo = (todoID) => {
    const newTodoList = todoList.filter((todoItem) => todoItem.id !== todoID);
    localStorage.setItem("todoList", JSON.stringify(newTodoList));
    setTodoList(newTodoList);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>TODOアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ye-connect.ico" />
      </Head>

      <main className={styles.main}>
        <h1 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6">Todo List</h1>
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-2">
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                autoFocus={true}
                type="text"
                placeholder="Todo List"
                value={todoTitle}
                onChange={(e) => setTodoTitle(e.target.value)}
              />
              
              <Button color="blue" textColor="black" buttonName="送信" func={addTodo}/>

          </div>
        </div>
        <div>
          {/** TODO List{JSON.stringify(todoList)} */}
          {/** TODO LIST UI */}
          <table className="table-auto">
            <thead>
              <tr>
                <th className="px-4 py-2">#</th>
                <th className="px-4 py-2">Title</th>
                <th className="px-4 py-2">Detail</th>
                <th className="px-4 py-2">Delete</th>
              </tr>
            </thead>
            <tbody>
              {todoList.map((todoItem, index) => (
                <tr className={index % 2 == 0 ? "" : "bg-gray-100"} key={index}>
                  <td className="border px-4 py-2">{index}</td>
                  <td className="border px-4 py-2">{todoItem.title}</td>
                  <td className="border px-4 py-2">
                    <Link
                      className="todo_item_title"
                      href={`/todo/${todoItem.id}`}
                    >
                      
                      <Button color="blue" textColor="black" buttonName="編集" />

                    </Link>
                  </td>
                  <td className="border px-4 py-2">
                    <Button color="red" textColor="black" buttonName="削除" func={() => {deleteTodo(todoItem.id)}}/>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.ye-connect.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/ye-connect.svg"
              alt="YECoonect Logo"
              width={30}
              height={30}
            />
          </span>
        </a>
      </footer>
    </div>
    
  );
}
